# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38e201ff42b3160cd52ed9e258a81a338c9dd67bdb75ed57a2a446ae7b252206ca0e39be8a68480cdfb48cce64a09f97eadecc481e492e8bc042e07c64453ee7

test:
  secret_key_base: 7630c7761de3d2d1906d1323236b36fc4559138e17c2ceeb40f79b6017296d371a026fa721a3678d248cb39cd548701d4e2a21613735b64aa7a53acd5211a8f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
